---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lenovo.
--- DateTime: 2025/7/7 19:28
---
-- 1.参数列表
-- 1.1 优惠券id
local voucherId = ARGV[1]
-- 1.2 用户id
local userId = ARGV[2]
-- 1.3 订单id
local orderId = ARGV[3]

-- 2.数据key
-- 2.1 库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2 订单key
local orderKey = 'seckill:order:' .. voucherId
-- 3.业务逻辑
-- 3.1 判断库存是否充足
local stock = tonumber(redis.call('get', stockKey))
if stock == nil then
    return 1 -- 库存 key 不存在，视为库存不足
end
if stock <= 0 then
    return 1 -- 库存不足
end

-- 3.2 判断用户是否下单
if(redis.call('sismember',orderKey,userId) == 1) then
    -- 3.3存在 说明重复下单
    return 2
end
-- 3.4 扣库存
redis.call('incrby',stockKey,-1)
--3.5 下单(保存用户)
redis.call('sadd',orderKey,userId)
-- 3.6 发送消息到队列中
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0